// アイテムバンク。IRTパラメータ(a: 識別力, b: 困難度, c: 当て推量)は
// TOEICレベル帯を想定した仮設定であり、実測校正値ではない。
// script の v は話者(A/B)。TTSで声を切り替える。

// テスト長プラン。問題数が多いほどθ事後分布が絞れて推定区間が狭くなる。
export const TEST_PLANS = {
  standard: {
    key: 'standard',
    label: '標準',
    minutes: 10,
    listening: { count: 8, timeLimitSec: 240 },
    reading: { count: 12, timeLimitSec: 360 },
  },
  thorough: {
    key: 'thorough',
    label: '精密',
    minutes: 15,
    listening: { count: 12, timeLimitSec: 360 },
    reading: { count: 18, timeLimitSec: 540 },
  },
};

export const listeningBank = [
  {
    id: 'L01', a: 1.1, b: -2.2, c: 0.25,
    script: [{ v: 'M', text: 'The meeting will start at three o\'clock in Room B.' }],
    question: 'What time will the meeting start?',
    options: ['At 1:00', 'At 2:00', 'At 3:00', 'At 4:00'],
    answer: 2,
    jaNote: '「three o\'clock」と明言されています。',
  },
  {
    id: 'L02', a: 1.0, b: -1.9, c: 0.25,
    script: [
      { v: 'W', text: 'Excuse me, where is the nearest post office?' },
      { v: 'M', text: 'It\'s across the street, next to the bank.' },
    ],
    question: 'Where is the post office?',
    options: ['Inside the station', 'Next to the bank', 'Behind the school', 'On the second floor'],
    answer: 1,
    jaNote: '「across the street, next to the bank(通りの向かい、銀行の隣)」と答えています。',
  },
  {
    id: 'L03', a: 1.2, b: -1.6, c: 0.25,
    script: [{ v: 'W', text: 'Attention, shoppers. The store will close in fifteen minutes. Please bring your items to the register.' }],
    question: 'What is being announced?',
    options: ['A new product sale', 'The store is closing soon', 'A lost child', 'Free samples at the entrance'],
    answer: 1,
    jaNote: '「close in fifteen minutes(15分後に閉店)」という閉店案内です。',
  },
  {
    id: 'L04', a: 1.1, b: -1.4, c: 0.25,
    script: [
      { v: 'M', text: 'Could you send me the sales report by Friday?' },
      { v: 'W', text: 'Sure. I\'ll email it to you tomorrow morning.' },
    ],
    question: 'What will the woman do?',
    options: ['Print the report', 'Email the report', 'Cancel the meeting', 'Call the client'],
    answer: 1,
    jaNote: '女性は「I\'ll email it(メールで送ります)」と言っています。',
  },
  {
    id: 'L05', a: 1.2, b: -1.2, c: 0.25,
    script: [{ v: 'M', text: 'Flight three-oh-two to Chicago has been delayed due to heavy snow. It will now depart at six thirty p.m.' }],
    question: 'Why has the flight been delayed?',
    options: ['Because of bad weather', 'Because of a mechanical problem', 'Because of a crew shortage', 'Because of airport construction'],
    answer: 0,
    jaNote: '「due to heavy snow(大雪のため)」= 悪天候が理由です。',
  },
  {
    id: 'L06', a: 1.3, b: -1.0, c: 0.25,
    script: [
      { v: 'W', text: 'Do you want to grab lunch at the new Italian place?' },
      { v: 'M', text: 'I\'d love to, but I have a meeting until one. Can we go after that?' },
    ],
    question: 'Why can\'t the man go to lunch now?',
    options: ['He is not hungry', 'He has a meeting', 'He brought his own lunch', 'The restaurant is closed'],
    answer: 1,
    jaNote: '「I have a meeting until one(1時まで会議がある)」と言っています。',
  },
  {
    id: 'L07', a: 1.0, b: -0.8, c: 0.25,
    script: [{ v: 'W', text: 'Thank you for calling Baxter Dental Clinic. Our office is open Monday through Friday, from nine a.m. to five p.m. To make an appointment, please press one.' }],
    question: 'What kind of business is this?',
    options: ['A hair salon', 'A law firm', 'A dental clinic', 'A travel agency'],
    answer: 2,
    jaNote: '冒頭で「Baxter Dental Clinic(歯科クリニック)」と名乗っています。',
  },
  {
    id: 'L08', a: 1.2, b: -0.6, c: 0.25,
    script: [
      { v: 'M', text: 'The printer on the second floor is out of order again.' },
      { v: 'W', text: 'I know. A technician is coming this afternoon. Until then, you can use the one near the elevator.' },
    ],
    question: 'What does the woman suggest the man do?',
    options: ['Repair the printer himself', 'Use a different printer', 'Call the technician', 'Work on another floor'],
    answer: 1,
    jaNote: '「you can use the one near the elevator(エレベーター近くのプリンターを使って)」と提案しています。',
  },
  {
    id: 'L09', a: 1.3, b: -0.4, c: 0.25,
    script: [{ v: 'M', text: 'Good morning, everyone. Before we open, I\'d like to remind you that the summer sale begins today. All clothing items are twenty percent off, and shoes are thirty percent off.' }],
    question: 'What discount is offered on shoes?',
    options: ['Ten percent', 'Twenty percent', 'Thirty percent', 'Forty percent'],
    answer: 2,
    jaNote: '衣類は20%オフ、靴は「thirty percent off(30%オフ)」です。',
  },
  {
    id: 'L10', a: 1.1, b: -0.2, c: 0.25,
    script: [
      { v: 'W', text: 'Have you finished reviewing the budget proposal?' },
      { v: 'M', text: 'Almost. I just need to check the travel expenses. I should be done by the end of the day.' },
    ],
    question: 'What does the man still need to do?',
    options: ['Approve the budget', 'Check the travel expenses', 'Book a business trip', 'Meet the accounting team'],
    answer: 1,
    jaNote: '「I just need to check the travel expenses(出張費の確認だけ残っている)」と言っています。',
  },
  {
    id: 'L11', a: 1.3, b: 0.0, c: 0.25,
    script: [
      { v: 'M', text: 'I heard the marketing position has finally been filled.' },
      { v: 'W', text: 'Yes, the new hire starts next Monday. She has over ten years of experience in digital advertising.' },
    ],
    question: 'What is mentioned about the new employee?',
    options: ['She used to work for a competitor', 'She has experience in digital advertising', 'She will manage the sales team', 'She requested a later start date'],
    answer: 1,
    jaNote: '「over ten years of experience in digital advertising」と経験に言及しています。',
  },
  {
    id: 'L12', a: 1.2, b: 0.2, c: 0.25,
    script: [{ v: 'W', text: 'Due to scheduled maintenance, the parking garage on Fifth Avenue will be closed this weekend. Employees are encouraged to use public transportation or the lot on Oak Street.' }],
    question: 'What are employees encouraged to do?',
    options: ['Work from home this weekend', 'Park on Fifth Avenue', 'Use public transportation or another lot', 'Postpone weekend shifts'],
    answer: 2,
    jaNote: '「use public transportation or the lot on Oak Street」と代替手段を勧めています。',
  },
  {
    id: 'L13', a: 1.4, b: 0.4, c: 0.25,
    script: [
      { v: 'W', text: 'The quarterly figures look better than expected.' },
      { v: 'M', text: 'True, but most of the growth came from overseas markets. Domestic sales were actually flat.' },
    ],
    question: 'What does the man imply?',
    options: ['The figures contain an error', 'Overseas offices will be expanded', 'Domestic sales did not grow', 'The next quarter will be worse'],
    answer: 2,
    jaNote: '「Domestic sales were actually flat(国内売上は横ばい)」→ 国内は成長していないことを示唆。',
  },
  {
    id: 'L14', a: 1.2, b: 0.6, c: 0.25,
    script: [{ v: 'M', text: 'Welcome to today\'s workshop on time management. We\'ll begin with a short self-assessment, followed by group exercises. Please note that the handouts will be available online after the session, so there\'s no need to take detailed notes.' }],
    question: 'Why is there no need to take detailed notes?',
    options: ['The session will be recorded', 'Materials will be posted online', 'Assistants will take notes', 'The content is in the textbook'],
    answer: 1,
    jaNote: '「handouts will be available online(資料は後日オンラインで入手可能)」だからです。',
  },
  {
    id: 'L15', a: 1.3, b: 0.9, c: 0.25,
    script: [
      { v: 'M', text: 'Weren\'t you supposed to be at the client presentation this morning?' },
      { v: 'W', text: 'It was pushed back to Thursday. The client had a scheduling conflict.' },
    ],
    question: 'What happened to the presentation?',
    options: ['It was canceled entirely', 'It was moved to another day', 'It was given by someone else', 'It was held online instead'],
    answer: 1,
    jaNote: '「pushed back to Thursday(木曜に延期された)」= 別の日に変更。',
  },
  {
    id: 'L16', a: 1.2, b: 1.2, c: 0.25,
    script: [{ v: 'W', text: 'Before we wrap up, a quick note about travel reimbursements. Starting next month, all expense reports must be submitted within two weeks of your return, and receipts under twenty-five dollars will no longer be required.' }],
    question: 'According to the speaker, what will no longer be necessary?',
    options: ['Submitting expense reports', 'Getting a manager\'s approval', 'Attaching small receipts', 'Booking through the travel desk'],
    answer: 2,
    jaNote: '「receipts under twenty-five dollars will no longer be required(25ドル未満の領収書は不要に)」。',
  },
  {
    id: 'L17', a: 1.4, b: 1.5, c: 0.25,
    script: [
      { v: 'W', text: 'The venue we booked for the conference just called. They\'re double-booked on the fifteenth.' },
      { v: 'M', text: 'You\'re kidding. Invitations went out last week. Changing the date now would look unprofessional.' },
      { v: 'W', text: 'Then let\'s ask about their sister property downtown.' },
    ],
    question: 'What does the woman suggest?',
    options: ['Postponing the conference', 'Holding the event at a different location', 'Sending new invitations', 'Canceling the venue contract'],
    answer: 1,
    jaNote: '日程変更は避けたいので「sister property downtown(系列の別会場)」を提案 = 場所の変更。',
  },
  {
    id: 'L18', a: 1.3, b: 1.8, c: 0.25,
    script: [{ v: 'M', text: 'Our customer satisfaction scores dipped slightly last quarter, but I wouldn\'t read too much into it. The survey methodology changed in June, and the new scale tends to produce lower numbers across the board. That said, the complaints about response time are worth taking seriously.' }],
    question: 'What does the speaker imply about the lower scores?',
    options: ['They reflect worsening service quality', 'They are largely due to a change in the survey method', 'They were caused by slower response times', 'They should be reported to management'],
    answer: 1,
    jaNote: '「methodology changed... tends to produce lower numbers」→ 低下は調査方法変更の影響が大きいと示唆。',
  },
  {
    id: 'L19', a: 1.3, b: 2.1, c: 0.25,
    script: [
      { v: 'M', text: 'If the shipment doesn\'t clear customs by Friday, we\'ll have to airfreight the replacement parts at our own expense.' },
      { v: 'W', text: 'Which would wipe out the margin on the entire order. Let\'s get the customs broker on the phone before we commit to anything.' },
    ],
    question: 'What is the woman concerned about?',
    options: ['Missing a customs deadline', 'Losing the profit on the order', 'Damaging the replacement parts', 'Switching to a new supplier'],
    answer: 1,
    jaNote: '「wipe out the margin(利益が消える)」= 注文の利益を失うことを懸念しています。',
  },
  {
    id: 'L20', a: 1.2, b: 2.4, c: 0.25,
    script: [{ v: 'W', text: 'Thank you all for coming on short notice. As you may have heard, the merger announcement has been moved up to next Tuesday, which means the press kits need to be finalized by Friday at the latest. Legal still hasn\'t signed off on the FAQ document, so until they do, treat every figure in it as provisional and don\'t share anything externally.' }],
    question: 'What does the speaker warn listeners not to do?',
    options: ['Miss the Friday deadline', 'Contact the legal department', 'Share information outside the company', 'Attend the press conference'],
    answer: 2,
    jaNote: '「don\'t share anything externally(社外に共有しないように)」と警告しています。',
  },
];

export const readingBank = [
  {
    id: 'R01', a: 1.0, b: -2.2, c: 0.25,
    question: 'The office ------- at 9 A.M. every day.',
    options: ['opens', 'open', 'opening', 'to open'],
    answer: 0,
    jaNote: '主語が三人称単数(The office)なので opens。',
  },
  {
    id: 'R02', a: 1.0, b: -2.0, c: 0.25,
    question: 'Please send the invoice ------- Ms. Tanaka by tomorrow.',
    options: ['to', 'on', 'at', 'of'],
    answer: 0,
    jaNote: 'send A to B「AをBに送る」。',
  },
  {
    id: 'R03', a: 1.1, b: -1.8, c: 0.25,
    question: 'Mr. Lee will ------- the sales meeting tomorrow afternoon.',
    options: ['attend', 'attends', 'attending', 'attendance'],
    answer: 0,
    jaNote: '助動詞 will の後は動詞の原形 attend。',
  },
  {
    id: 'R04', a: 1.0, b: -1.6, c: 0.25,
    question: 'The restaurant is famous ------- its fresh seafood.',
    options: ['for', 'with', 'to', 'about'],
    answer: 0,
    jaNote: 'be famous for 〜「〜で有名」。',
  },
  {
    id: 'R05', a: 1.1, b: -1.4, c: 0.25,
    question: 'Employees must wear ------- ID badges at all times.',
    options: ['their', 'they', 'them', 'theirs'],
    answer: 0,
    jaNote: '名詞 ID badges を修飾する所有格 their。',
  },
  {
    id: 'R06', a: 1.2, b: -1.2, c: 0.25,
    question: 'The annual report was ------- by the accounting team last week.',
    options: ['prepared', 'prepare', 'preparing', 'prepares'],
    answer: 0,
    jaNote: '受動態 be + 過去分詞 → was prepared。',
  },
  {
    id: 'R07', a: 1.1, b: -1.0, c: 0.25,
    question: '------- the heavy rain, the outdoor event was canceled.',
    options: ['Because of', 'Because', 'Since', 'As'],
    answer: 0,
    jaNote: '名詞句(the heavy rain)が続くので前置詞句 Because of。Because/Since/As は節を導く接続詞。',
  },
  {
    id: 'R08', a: 1.0, b: -0.9, c: 0.25,
    question: 'The new copier is much faster ------- the old one.',
    options: ['than', 'as', 'from', 'to'],
    answer: 0,
    jaNote: '比較級 faster と呼応するのは than。',
  },
  {
    id: 'R09', a: 1.2, b: -0.8, c: 0.25,
    question: 'Ms. Alvarez asked her assistant ------- the client files before noon.',
    options: ['to organize', 'organize', 'organizing', 'organized'],
    answer: 0,
    jaNote: 'ask + 人 + to do「人に〜するよう頼む」。',
  },
  {
    id: 'R10', a: 1.0, b: -0.7, c: 0.25,
    question: 'All visitors ------- sign in at the front desk before entering.',
    options: ['must', 'must to', 'have', 'ought'],
    answer: 0,
    jaNote: '助動詞 must + 原形。have なら have to、ought なら ought to が必要。',
  },
  {
    id: 'R11', a: 1.1, b: -0.6, c: 0.25,
    question: 'The store offers a ------- discount to first-time customers.',
    options: ['special', 'specially', 'specialize', 'specialty'],
    answer: 0,
    jaNote: '名詞 discount を修飾する形容詞 special。',
  },
  {
    id: 'R12', a: 1.1, b: -0.5, c: 0.25,
    question: 'We look forward to ------- from you soon.',
    options: ['hearing', 'hear', 'heard', 'hears'],
    answer: 0,
    jaNote: 'look forward to の to は前置詞なので動名詞 hearing。',
  },
  {
    id: 'R13', a: 1.2, b: -0.4, c: 0.25,
    question: '------- of the two proposals was approved by the board.',
    options: ['Neither', 'None', 'Not', 'No'],
    answer: 0,
    jaNote: '「2つのうちどちらも〜ない」は Neither。None は3つ以上に使う。',
  },
  {
    id: 'R14', a: 1.0, b: -0.3, c: 0.25,
    question: 'The seminar has been postponed ------- further notice.',
    options: ['until', 'by', 'for', 'in'],
    answer: 0,
    jaNote: 'until further notice「追って通知があるまで」(定型表現)。',
  },
  {
    id: 'R15', a: 1.1, b: -0.2, c: 0.25,
    question: 'Ms. Chen is responsible ------- training all new employees.',
    options: ['for', 'of', 'to', 'at'],
    answer: 0,
    jaNote: 'be responsible for 〜「〜に責任がある」。',
  },
  {
    id: 'R16', a: 1.2, b: -0.1, c: 0.25,
    question: 'Your package should arrive ------- three business days.',
    options: ['within', 'until', 'by the', 'at'],
    answer: 0,
    jaNote: 'within + 期間「〜以内に」。',
  },
  {
    id: 'R17', a: 1.2, b: 0.0, c: 0.25,
    question: '------- applicants must submit a résumé and two references.',
    options: ['Interested', 'Interesting', 'Interest', 'Interests'],
    answer: 0,
    jaNote: '「興味を持っている応募者」= 過去分詞 Interested が applicants を修飾。',
  },
  {
    id: 'R18', a: 1.3, b: 0.1, c: 0.25,
    question: 'The manager, ------- office is on the third floor, will see you shortly.',
    options: ['whose', 'who', 'whom', 'which'],
    answer: 0,
    jaNote: '直後の名詞 office につながる所有格の関係代名詞 whose。',
  },
  {
    id: 'R19', a: 1.1, b: 0.3, c: 0.25,
    question: 'Sales have increased ------- 15 percent since the campaign began.',
    options: ['by', 'at', 'in', 'with'],
    answer: 0,
    jaNote: '増減の幅を表す by「〜の分だけ」。',
  },
  {
    id: 'R20', a: 1.0, b: 0.5, c: 0.25,
    question: '------- signing the contract, please review the terms and conditions carefully.',
    options: ['Before', 'Ago', 'Until', 'Soon'],
    answer: 0,
    jaNote: 'Before + 動名詞「〜する前に」。',
  },
  {
    id: 'R21', a: 1.3, b: 0.7, c: 0.25,
    question: 'The committee has not yet reached a decision, ------- has it set a date for the next vote.',
    options: ['nor', 'or', 'so', 'but'],
    answer: 0,
    jaNote: '否定文を受けて「〜もまた…ない」は nor(後ろは倒置)。',
  },
  {
    id: 'R22', a: 1.1, b: 0.9, c: 0.25,
    question: 'Employees who complete the certification program are eligible ------- a salary increase.',
    options: ['for', 'to', 'with', 'of'],
    answer: 0,
    jaNote: 'be eligible for + 名詞「〜の資格がある」。be eligible to は動詞が続く。',
  },
  {
    id: 'R23', a: 1.2, b: 1.1, c: 0.25,
    question: '------- the CEO approves the budget, the project cannot move forward.',
    options: ['Unless', 'If', 'Provided', 'Once'],
    answer: 0,
    jaNote: '「承認しない限り前に進めない」= Unless(〜でない限り)。',
  },
  {
    id: 'R24', a: 1.2, b: 1.3, c: 0.25,
    question: 'The merger is expected to result in a workforce ------- of nearly ten percent.',
    options: ['reduction', 'reduce', 'reduced', 'reducing'],
    answer: 0,
    jaNote: '冠詞 a と of の間に入る名詞 reduction(workforce reduction「人員削減」)。',
  },
  {
    id: 'R25', a: 1.4, b: 1.5, c: 0.25,
    question: 'Had the shipment arrived on time, the production line ------- idle for three days.',
    options: ['would not have sat', 'will not sit', 'had not sat', 'does not sit'],
    answer: 0,
    jaNote: 'Had + 主語 + 過去分詞は仮定法過去完了の倒置 → 帰結節は would have + 過去分詞。',
  },
  {
    id: 'R26', a: 1.3, b: 1.7, c: 0.25,
    question: 'The proposal was rejected on the ------- that it exceeded the departmental budget.',
    options: ['grounds', 'reasons', 'causes', 'bases'],
    answer: 0,
    jaNote: 'on the grounds that 〜「〜という理由で」(定型表現)。',
  },
  {
    id: 'R27', a: 1.2, b: 1.9, c: 0.25,
    question: '------- in 1998, the firm has since expanded into twelve countries.',
    options: ['Founded', 'Founding', 'Having founded', 'To found'],
    answer: 0,
    jaNote: '主語 the firm は「設立される」側なので受動の分詞構文 Founded。',
  },
  {
    id: 'R28', a: 1.3, b: 2.1, c: 0.25,
    question: 'The auditor\'s findings were entirely ------- with the figures reported in the annual statement.',
    options: ['consistent', 'consisting', 'consisted', 'consistency'],
    answer: 0,
    jaNote: 'be consistent with 〜「〜と一致している」。',
  },
  {
    id: 'R29', a: 1.3, b: 2.3, c: 0.25,
    question: 'Only after the final inspection ------- to retailers.',
    options: ['will the products be released', 'the products will be released', 'the products are released', 'released will the products be'],
    answer: 0,
    jaNote: 'Only + 副詞句が文頭に来ると主語と助動詞が倒置 → will the products be released。',
  },
  {
    id: 'R30', a: 1.2, b: 2.6, c: 0.25,
    question: 'Applications submitted after the deadline will not be considered, ------- the circumstances.',
    options: ['whatever', 'however', 'whenever', 'wherever'],
    answer: 0,
    jaNote: 'whatever the circumstances (may be)「いかなる事情であれ」(譲歩の定型表現)。',
  },
  {
    id: 'RP1', a: 1.1, b: -0.5, c: 0.25,
    passage: 'To: All Staff\nSubject: Elevator Maintenance\n\nThe main elevator will be out of service on Tuesday, March 12, from 9 A.M. to noon. During this time, please use the stairs or the freight elevator at the rear of the building. We apologize for any inconvenience.',
    question: 'What are employees asked to do on Tuesday morning?',
    options: ['Work from home', 'Use the stairs or another elevator', 'Arrive after noon', 'Report to the rear entrance'],
    answer: 1,
    jaNote: '「please use the stairs or the freight elevator」と代替手段を指示しています。',
  },
  {
    id: 'RP2', a: 1.2, b: 0.4, c: 0.25,
    passage: 'GRAND OPENING — Riverside Fitness opens April 1!\n\nJoin in March and pay no enrollment fee — a savings of $50. In addition, the first fifty members will receive a complimentary personal training session. Visit our website for details.',
    question: 'How can customers avoid paying the enrollment fee?',
    options: ['By signing up before April', 'By booking a training session', 'By visiting the website', 'By referring a friend'],
    answer: 0,
    jaNote: '「Join in March and pay no enrollment fee」= 3月中(4月前)の入会で無料。',
  },
  {
    id: 'RP3', a: 1.3, b: 1.2, c: 0.25,
    passage: 'Dear Mr. Okada,\n\nThank you for your order (#4417). Unfortunately, the desk lamp you requested is currently out of stock. We expect a new shipment within two weeks. If you prefer, we can substitute a similar model at the same price, or issue a full refund. Please let us know how you would like to proceed.\n\nCustomer Service, Hartley Home Goods',
    question: 'Why was the email sent?',
    options: ['To confirm a delivery date', 'To explain that an item is unavailable', 'To request an additional payment', 'To advertise a similar product'],
    answer: 1,
    jaNote: '「out of stock(在庫切れ)」の連絡と代替案の提示が目的です。',
  },
  {
    id: 'RP4', a: 1.3, b: 2.0, c: 0.25,
    passage: 'MEMO — Retention Committee Findings\n\nWhile overall turnover remains below the industry average, exit interviews indicate that limited advancement opportunities — rather than compensation — are the primary reason employees leave. Accordingly, the committee recommends piloting an internal mobility program before revisiting the salary structure.',
    question: 'What does the committee suggest doing first?',
    options: ['Raising salaries across the board', 'Conducting more exit interviews', 'Launching an internal mobility program', 'Benchmarking against industry turnover'],
    answer: 2,
    jaNote: '「recommends piloting an internal mobility program before revisiting the salary structure」→ 給与見直しの前に社内異動プログラムを試行。',
  },
  {
    id: 'RP5', a: 1.1, b: -0.8, c: 0.25,
    passage: 'SPRING SALE at Delmar Shoes!\n\nAll sneakers 25% off from March 1 to March 7. Members receive an additional 10% discount at the register. Open daily, 10 A.M. to 8 P.M.',
    question: 'How long will the sale last?',
    options: ['Three days', 'One week', 'Two weeks', 'One month'],
    answer: 1,
    jaNote: '「from March 1 to March 7」= 7日間 = 1週間です。',
  },
  {
    id: 'RP6', a: 1.2, b: 0.6, c: 0.25,
    passage: 'NOW HIRING — Part-Time Café Staff\n\nRiver Bean Café is looking for friendly part-time staff for weekend shifts. No experience necessary — full training provided. Free drinks during shifts. Apply in person at 22 Harbor Street or online at riverbean.example.com.',
    question: 'What is indicated about the position?',
    options: ['It requires previous experience', 'It is a full-time role', 'Training will be provided', 'It is limited to weekday shifts'],
    answer: 2,
    jaNote: '「No experience necessary — full training provided」= 経験不問で研修あり。',
  },
  {
    id: 'RP7', a: 1.3, b: 1.4, c: 0.25,
    passage: 'GreenBox Meal Kits — Fresh ingredients, delivered weekly.\n\nNew subscribers who sign up by June 30 receive their first two boxes at half price. Skip a week or cancel anytime. Please note that this promotion cannot be combined with any other offer and applies to standard plans only.',
    question: 'What is true about the promotional discount?',
    options: ['It applies to all subscription plans', 'It requires a one-year commitment', 'It cannot be used with other offers', 'It covers the first four deliveries'],
    answer: 2,
    jaNote: '「cannot be combined with any other offer(他の特典との併用不可)」と明記されています。',
  },
];
